package com.nextArt.community.mapper;

import com.nextArt.community.model.Question;
import com.nextArt.community.model.QuestionModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestionModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Jan 11 16:17:51 CST 2020
     */
    long countByExample(QuestionModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Jan 11 16:17:51 CST 2020
     */
    int deleteByExample(QuestionModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Jan 11 16:17:51 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Jan 11 16:17:51 CST 2020
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Jan 11 16:17:51 CST 2020
     */
    int insertSelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Jan 11 16:17:51 CST 2020
     */
    List<Question> selectByExampleWithBLOBs(QuestionModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Jan 11 16:17:51 CST 2020
     */
    List<Question> selectByExample(QuestionModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Jan 11 16:17:51 CST 2020
     */
    Question selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Jan 11 16:17:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") Question record, @Param("example") QuestionModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Jan 11 16:17:51 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Question record, @Param("example") QuestionModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Jan 11 16:17:51 CST 2020
     */
    int updateByExample(@Param("record") Question record, @Param("example") QuestionModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Jan 11 16:17:51 CST 2020
     */
    int updateByPrimaryKeySelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Jan 11 16:17:51 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat Jan 11 16:17:51 CST 2020
     */
    int updateByPrimaryKey(Question record);
}